name: Check branches

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check develop -> master
        run: |
          if [ "${{ github.base_ref }}" == "master" ] && [ "${{ github.head_ref }}" != "develop" ]
          then
            echo "Error: Pull-request into master from a feature branch";
            exit 1;
          fi
